### ISSUE TITLE
Gerbers for v0.3c ?

### ISSUE THREAD

**Issue by chechu2k5** [LeafCutterLabs/miniMACRO5#10]
Hi!

First off, many thanks for making this amazing PCB! 
I had purchased a set of these PCBs from your Tindie store and had received the boards with the date 04/15/2020 v.3c printed on the silkscreen. I was looking for the corresponding gerber files in this repo but only found the ones for v3(indvidual) and v3b (panelized). Any chance you could upload the ones for the version I have ?

I think it would be immensely useful if you could tag specific commits as releases and/or populate a CHANGES file to let others know what's changed, fixed or improved. I am curious if there are any specific issues with the v3 and v3b that are fixed in v3c ?

Thanks

![IMG_20210105_144410](https://user-images.githubusercontent.com/5258640/103708945-684bf900-4f66-11eb-9eb4-be7286b6d890.jpg)

**Comment by LeafCutterLabs** [comment]
Thank you for pointing it out to me and I really need to improve my documentation. I can't really remember from 9 months ago but I think just the mounting holes in the middle were added. I just added the newest gerber/eagle files and will have a change log going forward.
