### ISSUE TITLE
BOM missing part number for reset switch

### ISSUE THREAD

**Issue by JellyTitan** [LeafCutterLabs/miniMACRO5#12]
The BOM has no part number for the reset switch. Do you happen to have a digikey part number for it?

**Comment by LeafCutterLabs** [comment]
Not sure on digikey but most 5.1 smd switches should work:
https://lcsc.com/product-detail/Tactile-Switches_XKB-Connectivity-TS-1187A-B-A-B_C318884.html

**Comment by JellyTitan** [comment]
Thanks for the update! I'll put in a pull request with an updated BOM, and a note about jumping to flash.
