### ISSUE TITLE
Two ground pins should or should not short? 

### ISSUE THREAD

**Issue by JellyTitan** [LeafCutterLabs/miniMACRO5#14]
Step 2a states that no two pins should short after soldering on the pro micro headers. Testing the board before the headers are attached, it looks like the two GND pins next to each other short. Is this working as intended?

**Comment by ghost** [comment]
That is indeed correct. The third and fourth pin on one side should be shorted when measuring with a multimeter. And each of them should in turn short with the second pin (also GND) on the opposite side.
