### ISSUE TITLE
Gerber files for v3b board required

### ISSUE THREAD

**Issue by joncojonathan** [LeafCutterLabs/miniMACRO5#6]
It would appear the v3b board Gerber files are missing from the repo.  [This file](https://github.com/joncojonathan/miniMACRO5/blob/master/hardware/v3gerber.zip) is for the v3 board (dated 2020-02-16), however, the current boards being sold appear to be a later revision, v3b (dated 2020-03-15).

Please could the v3b Gerber files be uploaded, potentially deprecating the older file?  I note on the v3 PCB layout the pins are in a slightly different location.  It appears the drill scaling may also be off (I'm not familiar with making PCBs, a friend had to explain).

Many thanks for all your work on this @LeafCutterLabs.

**Comment by mariemat** [comment]
I've seen this too. Layers from V3 PCB are not aligned correctly, it seems.
![pcb](https://user-images.githubusercontent.com/16922356/83490999-4f033b80-a4b1-11ea-892f-d901c99354d4.jpg)

**Comment by LeafCutterLabs** [comment]
Uploaded the v3b board. The holes line up but there is a difference between the plated holes and regular drills. The non-plated holes are for the encoder mechanical attachment and 5th holes on the Cherry MX footprint.

**Comment by joncojonathan** [comment]
Many thanks @LeafCutterLabs .
