### ISSUE TITLE
hardware/v3b/v3b-plate.stl actually the case

### ISSUE THREAD

**Issue by joncojonathan** [LeafCutterLabs/miniMACRO5#9]
Thanks for the v3b case files at `hardware/v3b/`.  I've noticed the plate (`v3b-plate.stl`) is actually another copy of the case, and `md5sum` shows they're the same file but with different names.

Please could you provide the plate for v3b?  Many thanks.

```md5sum
0ece18a04be3ff5536e263b6578191e7  v3b-case.stl
0ece18a04be3ff5536e263b6578191e7  v3b-plate.stl
```

**Comment by joncojonathan** [comment]
Edited issue to correct a typo.  The two STL files are both the case, so the plate is missing.

**Comment by LeafCutterLabs** [comment]
Corrected
